### ISSUE TITLE
Is it running as a host or a semi machine?

### ISSUE THREAD

**Issue by lhf552004** [ostigter/secs4j#1]
Hi ,I'm running TestTool.java in the package org.ozsoft.secs4j.gui. Is it running as host or a semi machine?
I'm confusing.

**Comment by ostigter** [comment]
Hi,

Thanks for looking into secs4j! It's been 4 years since I last worked on it (nor will I likely ever work on it again), so I don't remember any details, but from looking at the source code I conclude that the tool can be run either in Active or Passive mode, so it should be able to simulate both a (driving) host and a (listening) semi-machine.

**Comment by lhf552004** [comment]
Thank you.
